# Generated by Django 5.2.6 on 2025-09-20 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='作品名')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='スラッグ')),
                ('description', models.TextField(verbose_name='概要')),
                ('detailed_description', models.TextField(blank=True, verbose_name='詳細説明')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='portfolio_thumbnails/', verbose_name='サムネイル')),
                ('video_url', models.URLField(blank=True, verbose_name='紹介動画URL')),
                ('live_site_url', models.URLField(blank=True, verbose_name='公開先URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('blog_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolios', to='blog.post', verbose_name='関連ブログ記事')),
            ],
            options={
                'verbose_name': 'ポートフォリオ',
                'verbose_name_plural': 'ポートフォリオ',
                'ordering': ['-created_at'],
            },
        ),
    ]
