# Generated by Django 5.2.6 on 2025-09-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_options_remove_portfolio_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='技術名')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='スラッグ')),
            ],
            options={
                'verbose_name': '技術スタック',
                'verbose_name_plural': '技術スタック',
            },
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='スラッグ'),
        ),
    ]
