# Generated by Django 5.2.6 on 2025-09-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_techstack_alter_portfolio_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techstack',
            options={},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='portfolios', to='portfolio.techstack', verbose_name='技術スタック'),
        ),
    ]
