# Generated by Django 5.2.6 on 2025-09-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_techstack_options_portfolio_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='video_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='紹介動画ID'),
        ),
    ]
